[package]
name = "hack"
version = "1.0.0"
edition = "2021"
license = "MIT OR Apache-2.0 OR CC0-1.0"
publish = false

[dependencies]
# As downstream crates lie about their minimum required versions.
backtrace = "0.3.51"
