[package]
name = "harness"
version = "1.0.0"
edition = "2021"
license = "MIT OR Apache-2.0 OR CC0-1.0"
publish = false

[dependencies]
camino = "1.1.6"
cargo_metadata = "0.18.0"
clap = { version = "4.0.27", features = [ "derive" ] }

reves.path = "../reves"

[lints]
workspace = true
