[package]
name = "lily"
version = "1.0.0"
edition = "2021"
license = "MIT OR Apache-2.0 OR CC0-1.0"
publish = false
links = "daffodil"

[dependencies]
# unused
buttercup.workspace = true

lantana.workspace = true
